"""tests/test_check_agents_sync.py — pytest suite for scripts/check_agents_sync.py.

All tests use synthetic in-memory or temporary-file fixtures — no real repo
files are read.  The fixture-based approach keeps the suite hermetic and fast:
it proves drift-detection logic independently of whatever state the real
worktree is in.

Coverage
--------
D1  shim key present in ROUTING.md but no shim file → drift detected.
D2  shim file exists but key absent from ROUTING.md → drift detected.
D3  shim ``name:`` field mismatches its filename stem → drift detected.
D4  shim ``model:`` field is not a valid tier → drift detected.
D5  shim ``model:`` is missing entirely → drift detected.
D6  shim model differs from policy table → drift detected.
D7  policy model matches shim → no drift.
D8  all in sync (no policy) → clean exit 0.
D9  all in sync (with policy) → clean exit 0.
D10 missing ``name:`` in shim → drift detected.
D11 SKIP_KEYS are excluded from cross-check.
D12 main() integration — in-sync fixture tree exits 0, drifted tree exits 1.
D13 main() with missing agents dir exits 2.
D14 main() with missing ROUTING.md exits 2.
D15 policy absent, --strict flag → exits 2.
D16 policy absent, no --strict → clean pass (prints policy not yet in-tree).
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

import pytest

# Ensure scripts/ is importable regardless of how pytest is invoked.
_REPO_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(_REPO_ROOT / "scripts"))

from check_agents_sync import (  # noqa: E402
    SKIP_KEYS,
    VALID_MODELS,
    check_sync,
    load_policy_models,
    load_routing,
    load_shims,
    main,
    parse_frontmatter,
)

# ---------------------------------------------------------------------------
# Helpers / shared fixtures
# ---------------------------------------------------------------------------

_BASE_ROUTING = textwrap.dedent(
    """\
    # Role routing — reviewer/manager per role

    > Generated by scripts/gen_subagents.py — do not edit by hand.

    | Role key | Display name | Dept | Reports to (reviewer) |
    |---|---|---|---|
    | `qa-eng` | QA Engineer | engineering | QA Lead |
    | `cto` | CTO | engineering | CEO |
    | `backend-eng-1` | Backend Engineer 1 | engineering | Backend EM |
    """
)

_KNOWN_ROLES = frozenset({"qa-eng", "cto", "backend-eng-1"})


def make_shim(key: str, model: str = "sonnet", name: str = "") -> dict[str, str]:
    """Return a minimal shim frontmatter dict."""
    return {
        "name": name or key,
        "model": model,
        "description": f"DasLab engineering role — {key}.",
    }


def make_routing_dict(keys: list[str]) -> dict[str, str]:
    """Return a routing dict ``{role_key: reports_to}``."""
    return dict.fromkeys(keys, "some-manager")


def write_shim_file(tmp_path: Path, key: str, fm: dict[str, str]) -> Path:
    """Write a ``.claude/agents/<key>.md`` shim file and return its path."""
    agents_dir = tmp_path / ".claude" / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    lines = ["---"]
    for k, v in fm.items():
        lines.append(f"{k}: {v}")
    lines += ["---", "", "You are a DasLab agent.", ""]
    path = agents_dir / f"{key}.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_routing_file(tmp_path: Path, content: str) -> Path:
    """Write a ROUTING.md to *tmp_path*/board/ROUTING.md and return its path."""
    board_dir = tmp_path / "board"
    board_dir.mkdir(parents=True, exist_ok=True)
    path = board_dir / "ROUTING.md"
    path.write_text(content, encoding="utf-8")
    return path


def write_policy_file(tmp_path: Path, rows: dict[str, str]) -> Path:
    """Write a minimal model-allocation.md to *tmp_path*/governance/policies/."""
    policy_dir = tmp_path / "governance" / "policies"
    policy_dir.mkdir(parents=True, exist_ok=True)
    lines = ["# Model allocation", "", "| Role | Model | Rationale |", "|---|---|---|"]
    for key, model in rows.items():
        lines.append(f"| `{key}` | {model} | test |")
    path = policy_dir / "model-allocation.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# D1 — shim key in ROUTING.md but no shim file
# ---------------------------------------------------------------------------


def test_routing_key_no_shim_detected() -> None:
    """Role in ROUTING.md with no matching shim file triggers drift."""
    shims: dict[str, dict[str, str]] = {}  # empty — no shims at all
    routing = make_routing_dict(["qa-eng"])
    errors = check_sync(shims, routing, policy_models=None)
    assert any("ROUTING.md" in e and "qa-eng" in e for e in errors), errors


# ---------------------------------------------------------------------------
# D2 — shim exists but key absent from ROUTING.md
# ---------------------------------------------------------------------------


def test_shim_key_not_in_routing_detected() -> None:
    """Shim file whose key is absent from ROUTING.md triggers drift."""
    shims = {"ghost-role": make_shim("ghost-role")}
    routing: dict[str, str] = {}  # empty — no routing rows
    errors = check_sync(shims, routing, policy_models=None)
    assert any("ghost-role" in e and "ROUTING.md" in e for e in errors), errors


# ---------------------------------------------------------------------------
# D3 — shim name: field mismatches filename stem
# ---------------------------------------------------------------------------


def test_name_mismatch_detected() -> None:
    """When shim ``name:`` does not match its key (filename stem), it is drift."""
    shims = {"qa-eng": make_shim("qa-eng", name="wrong-name")}
    routing = make_routing_dict(["qa-eng"])
    errors = check_sync(shims, routing, policy_models=None)
    assert any("name" in e and "qa-eng" in e for e in errors), errors
    assert any("wrong-name" in e for e in errors), errors


# ---------------------------------------------------------------------------
# D4 — model field not a valid tier
# ---------------------------------------------------------------------------


def test_invalid_model_tier_detected() -> None:
    """A model value outside {opus, sonnet, haiku} triggers drift."""
    shims = {"qa-eng": make_shim("qa-eng", model="gpt-4")}
    routing = make_routing_dict(["qa-eng"])
    errors = check_sync(shims, routing, policy_models=None)
    assert any("model" in e and "gpt-4" in e for e in errors), errors


def test_all_valid_models_accepted() -> None:
    """Each of the four valid model tiers produces no model-tier error."""
    routing = make_routing_dict(["qa-eng"])
    for model in VALID_MODELS:
        shims = {"qa-eng": make_shim("qa-eng", model=model)}
        errors = check_sync(shims, routing, policy_models=None)
        tier_errors = [e for e in errors if "not a valid tier" in e]
        assert not tier_errors, f"model '{model}' unexpectedly flagged: {errors}"


# ---------------------------------------------------------------------------
# D5 — model field missing entirely
# ---------------------------------------------------------------------------


def test_missing_model_field_detected() -> None:
    """Shim with no ``model:`` key triggers drift."""
    shims = {"qa-eng": {"name": "qa-eng", "description": "test"}}  # no model key
    routing = make_routing_dict(["qa-eng"])
    errors = check_sync(shims, routing, policy_models=None)
    assert any("model" in e and "qa-eng" in e for e in errors), errors


# ---------------------------------------------------------------------------
# D6 — shim model differs from policy table
# ---------------------------------------------------------------------------


def test_model_policy_mismatch_detected() -> None:
    """When policy says opus but shim says sonnet, drift is reported."""
    shims = {"qa-eng": make_shim("qa-eng", model="sonnet")}
    routing = make_routing_dict(["qa-eng"])
    policy = {"qa-eng": "opus"}  # policy says opus
    errors = check_sync(shims, routing, policy_models=policy)
    assert any("differs from policy" in e for e in errors), errors
    assert any("qa-eng" in e for e in errors), errors


# ---------------------------------------------------------------------------
# D7 — shim model matches policy → no drift
# ---------------------------------------------------------------------------


def test_model_policy_match_accepted() -> None:
    """When shim model matches the policy table, no drift is reported."""
    shims = {"qa-eng": make_shim("qa-eng", model="sonnet")}
    routing = make_routing_dict(["qa-eng"])
    policy = {"qa-eng": "sonnet"}
    errors = check_sync(shims, routing, policy_models=policy)
    assert not errors, errors


# ---------------------------------------------------------------------------
# D8 — all in sync, no policy → clean
# ---------------------------------------------------------------------------


def test_clean_no_policy() -> None:
    """Fully matching shims and ROUTING.md with no policy → zero errors."""
    keys = ["qa-eng", "cto", "backend-eng-1"]
    shims = {k: make_shim(k) for k in keys}
    routing = make_routing_dict(keys)
    errors = check_sync(shims, routing, policy_models=None)
    assert not errors, errors


# ---------------------------------------------------------------------------
# D9 — all in sync, with policy → clean
# ---------------------------------------------------------------------------


def test_clean_with_policy() -> None:
    """Fully matching shims, ROUTING.md, and policy → zero errors."""
    keys = ["qa-eng", "cto"]
    models = {"qa-eng": "sonnet", "cto": "opus"}
    shims = {k: make_shim(k, model=models[k]) for k in keys}
    routing = make_routing_dict(keys)
    errors = check_sync(shims, routing, policy_models=models)
    assert not errors, errors


# ---------------------------------------------------------------------------
# D10 — name: field missing entirely
# ---------------------------------------------------------------------------


def test_missing_name_field_detected() -> None:
    """Shim with no ``name:`` key triggers drift."""
    shims = {"qa-eng": {"model": "sonnet", "description": "test"}}  # no name key
    routing = make_routing_dict(["qa-eng"])
    errors = check_sync(shims, routing, policy_models=None)
    assert any("name" in e and "qa-eng" in e for e in errors), errors


# ---------------------------------------------------------------------------
# D11 — SKIP_KEYS are excluded from cross-check
# ---------------------------------------------------------------------------


def test_skip_keys_are_excluded(tmp_path: Path) -> None:
    """External-runtime pilots in SKIP_KEYS do not count as shim files."""
    agents_dir = tmp_path / ".claude" / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)

    # Write a shim for a SKIP key — it must be ignored by load_shims
    for skip_key in SKIP_KEYS:
        fm = make_shim(skip_key)
        write_shim_file(tmp_path, skip_key, fm)

    shims = load_shims(agents_dir)
    for skip_key in SKIP_KEYS:
        assert skip_key not in shims, f"SKIP key '{skip_key}' leaked into shims"


# ---------------------------------------------------------------------------
# D12 — main() integration: in-sync tree exits 0, drifted tree exits 1
# ---------------------------------------------------------------------------


def test_main_in_sync(tmp_path: Path) -> None:
    """main() returns 0 when agents and ROUTING.md are in sync."""
    key = "qa-eng"
    write_shim_file(tmp_path, key, make_shim(key))
    routing_path = write_routing_file(
        tmp_path,
        _BASE_ROUTING,  # contains qa-eng, cto, backend-eng-1
    )
    # Write shims for all three roles in the routing table. Models must match
    # the real policy table (read by main() when no --policy is given): cto is
    # opus, backend-eng-1 is sonnet.
    write_shim_file(tmp_path, "cto", make_shim("cto", model="opus"))
    write_shim_file(tmp_path, "backend-eng-1", make_shim("backend-eng-1"))

    agents_dir = tmp_path / ".claude" / "agents"
    rc = main(
        [
            "--agents", str(agents_dir),
            "--routing", str(routing_path),
        ]
    )
    assert rc == 0, f"Expected exit 0 but got {rc}"


def test_main_drifted(tmp_path: Path) -> None:
    """main() returns 1 when a shim is missing from ROUTING.md."""
    write_shim_file(tmp_path, "orphan-role", make_shim("orphan-role"))
    routing_path = write_routing_file(tmp_path, _BASE_ROUTING)  # no orphan-role row
    agents_dir = tmp_path / ".claude" / "agents"
    rc = main(
        [
            "--agents", str(agents_dir),
            "--routing", str(routing_path),
        ]
    )
    assert rc == 1, f"Expected exit 1 (drift) but got {rc}"


# ---------------------------------------------------------------------------
# D13 — main() with missing agents dir → exits 2
# ---------------------------------------------------------------------------


def test_main_missing_agents_dir(tmp_path: Path) -> None:
    """main() returns 2 when the agents directory does not exist."""
    routing_path = write_routing_file(tmp_path, _BASE_ROUTING)
    rc = main(
        [
            "--agents", str(tmp_path / "nonexistent-agents"),
            "--routing", str(routing_path),
        ]
    )
    assert rc == 2


# ---------------------------------------------------------------------------
# D14 — main() with missing ROUTING.md → exits 2
# ---------------------------------------------------------------------------


def test_main_missing_routing(tmp_path: Path) -> None:
    """main() returns 2 when ROUTING.md does not exist."""
    agents_dir = tmp_path / ".claude" / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    rc = main(
        [
            "--agents", str(agents_dir),
            "--routing", str(tmp_path / "nonexistent" / "ROUTING.md"),
        ]
    )
    assert rc == 2


# ---------------------------------------------------------------------------
# D15 — policy absent + --strict → exits 2
# ---------------------------------------------------------------------------


def test_main_strict_missing_policy(tmp_path: Path) -> None:
    """main() returns 2 when --strict is set and policy file is absent."""
    write_shim_file(tmp_path, "qa-eng", make_shim("qa-eng"))
    routing_path = write_routing_file(tmp_path, _BASE_ROUTING)
    # Write shims for all ROUTING.md roles so cross-check passes
    for role in ["cto", "backend-eng-1"]:
        write_shim_file(tmp_path, role, make_shim(role))

    agents_dir = tmp_path / ".claude" / "agents"
    rc = main(
        [
            "--agents", str(agents_dir),
            "--routing", str(routing_path),
            "--policy", str(tmp_path / "nonexistent-policy.md"),
            "--strict",
        ]
    )
    assert rc == 2


# ---------------------------------------------------------------------------
# D16 — policy absent, no --strict → clean pass
# ---------------------------------------------------------------------------


def test_main_no_strict_missing_policy(tmp_path: Path, capsys: pytest.CaptureFixture) -> None:
    """main() returns 0 and prints 'policy not yet in-tree' when policy absent."""
    for role in ["qa-eng", "cto", "backend-eng-1"]:
        write_shim_file(tmp_path, role, make_shim(role))
    routing_path = write_routing_file(tmp_path, _BASE_ROUTING)
    agents_dir = tmp_path / ".claude" / "agents"

    rc = main(
        [
            "--agents", str(agents_dir),
            "--routing", str(routing_path),
            "--policy", str(tmp_path / "nonexistent-policy.md"),
        ]
    )
    captured = capsys.readouterr()
    assert rc == 0, f"Expected exit 0 but got {rc}; stdout={captured.out}"
    assert "policy not yet in-tree" in captured.out


# ---------------------------------------------------------------------------
# parse_frontmatter unit tests
# ---------------------------------------------------------------------------


def test_parse_frontmatter_basic() -> None:
    """parse_frontmatter extracts simple key:value pairs."""
    text = "---\nname: qa-eng\nmodel: sonnet\n---\nbody\n"
    fm = parse_frontmatter(text)
    assert fm["name"] == "qa-eng"
    assert fm["model"] == "sonnet"


def test_parse_frontmatter_quoted_values() -> None:
    """parse_frontmatter strips YAML double-quotes from values."""
    text = '---\nname: "qa-eng"\nmodel: "sonnet"\n---\nbody\n'
    fm = parse_frontmatter(text)
    assert fm["name"] == "qa-eng"
    assert fm["model"] == "sonnet"


def test_parse_frontmatter_missing_returns_empty() -> None:
    """parse_frontmatter returns an empty dict when frontmatter is absent."""
    fm = parse_frontmatter("no frontmatter here\n")
    assert fm == {}


# ---------------------------------------------------------------------------
# load_routing / load_policy_models unit tests
# ---------------------------------------------------------------------------


def test_load_routing_parses_table(tmp_path: Path) -> None:
    """load_routing returns {role_key: reports_to} for each table row."""
    path = write_routing_file(tmp_path, _BASE_ROUTING)
    routing = load_routing(path)
    assert "qa-eng" in routing
    assert "cto" in routing
    assert "backend-eng-1" in routing
    assert "nonexistent" not in routing


def test_load_policy_models_parses_table(tmp_path: Path) -> None:
    """load_policy_models returns {role_key: model} for each table row."""
    policy_path = write_policy_file(tmp_path, {"qa-eng": "sonnet", "cto": "opus"})
    models = load_policy_models(policy_path)
    assert models is not None
    assert models["qa-eng"] == "sonnet"
    assert models["cto"] == "opus"


def test_load_policy_models_absent_returns_none(tmp_path: Path) -> None:
    """load_policy_models returns None when the file does not exist."""
    result = load_policy_models(tmp_path / "nonexistent.md")
    assert result is None


# ---------------------------------------------------------------------------
# load_shims — file-system round-trip
# ---------------------------------------------------------------------------


def test_load_shims_roundtrip(tmp_path: Path) -> None:
    """write a shim file, load it back, and verify frontmatter is intact."""
    fm = make_shim("qa-eng", model="sonnet")
    write_shim_file(tmp_path, "qa-eng", fm)
    agents_dir = tmp_path / ".claude" / "agents"
    loaded = load_shims(agents_dir)
    assert "qa-eng" in loaded
    assert loaded["qa-eng"]["name"] == "qa-eng"
    assert loaded["qa-eng"]["model"] == "sonnet"
