#!/usr/bin/env python3
"""gen_org.py — generate org constants from the Org Schema.

Prisma's pattern, Python-native: org/schema.daslab.yaml is the single declarative
SSOT; this emits the GENERATED module scripts/_org_generated.py (NEVER_AUTO_APPROVE,
GATES, ROLES, GATE_OWNERS) that the validators consume — so enforcement can never
drift from the schema (push-errors-left). The output is deterministic; the drift
gate (check_org_drift.py) regenerates and diffs against the committed file.

Usage:
    python3 scripts/gen_org.py            # write scripts/_org_generated.py
    python3 scripts/gen_org.py --check    # print the rendered module (no write)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from _paths import ROOT

try:
    import yaml
except ImportError:  # pragma: no cover - environment guard
    sys.stderr.write("PyYAML required: pip install pyyaml\n")
    sys.exit(2)

SCHEMA_PATH = ROOT / "org" / "schema.daslab.yaml"
GENERATED_PATH = ROOT / "scripts" / "_org_generated.py"

_BANNER = (
    "# DO NOT EDIT — generated by scripts/gen_org.py from org/schema.daslab.yaml.\n"
    "# Regenerate: python3 scripts/gen_org.py   |   drift gate: scripts/check_org_drift.py\n"
    "# ruff: noqa\n"
    '"""Generated org constants. The validators import these so they '
    'cannot drift from the Org Schema."""\n'
)


def load_schema(path: Path = SCHEMA_PATH) -> dict:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    return data if isinstance(data, dict) else {}


def _gate_owners(roles: dict) -> dict[str, tuple]:
    owners: dict[str, list[str]] = {}
    for role, spec in roles.items():
        gates = (spec or {}).get("gate_owner", [])
        gates = gates if isinstance(gates, list) else [gates]
        for g in gates:
            owners.setdefault(str(g), []).append(str(role))
    return {g: tuple(sorted(owners[g])) for g in sorted(owners)}


def render(schema: dict) -> str:
    """Deterministic source for scripts/_org_generated.py."""
    never = tuple(str(x) for x in schema.get("never_auto_approve", []))
    gates = tuple(str(x) for x in schema.get("gates", []))
    roles = schema.get("roles", {}) or {}
    role_keys = tuple(sorted(str(r) for r in roles))
    gate_owners = _gate_owners(roles)
    lines = [
        _BANNER,
        f"NEVER_AUTO_APPROVE = {never!r}",
        f"GATES = {gates!r}",
        f"ROLES = {role_keys!r}",
        f"GATE_OWNERS = {gate_owners!r}",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--schema", type=Path, default=SCHEMA_PATH)
    ap.add_argument("--out", type=Path, default=GENERATED_PATH)
    ap.add_argument("--check", action="store_true", help="print the rendered module, do not write")
    args = ap.parse_args(argv)

    if not args.schema.is_file():
        sys.stderr.write(f"ERROR: Org Schema not found: {args.schema}\n")
        return 2
    rendered = render(load_schema(args.schema))

    if args.check:
        sys.stdout.write(rendered)
        return 0
    args.out.write_text(rendered, encoding="utf-8")
    print(f"generated {args.out.relative_to(ROOT)} from {args.schema.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
